/**
 * Client runtime injected constant block for dashboard script.
 */

import {
  EQUILIBRIUM_DYNAMIC_CRI_MIN,
  EQUILIBRIUM_GUARD_CRI_MIN,
  ROOT8_SLIPPAGE_LOCK_LABEL,
  R1018_SLIPPAGE_LOCK_LABEL,
  ROOT_DEFENSE_ELEVATED_MIN,
  ROOT_DEFENSE_OPTIMAL_MIN,
} from "../../../config/constants";
import {
  DYNAMIC_MAX_SL_BALANCE_RATE,
  DYNAMIC_MAX_SL_BASE_USD,
  DEFAULT_ACCOUNT_EQUITY_USD,
  DAILY_LOSS_CAP_MULTIPLIER,
  MAX_DAILY_SL_COUNT,
} from "../../../services/effective-max-sl";
import {
  ROOT_DEFENSE_MATRIX_HUD_CONFIG,
  ROOT_DEFENSE_SCORE_MAX,
  ROOT_DEFENSE_SCORE_MIN,
  ROOT_DEFENSE_TIER_4_ROOTS,
  ROOT_DEFENSE_TIER_PENALTY_BY_ROOT,
} from "../../../services/cri-engine";
import {
  CRI_TIER_DEFINITIONS,
  RISK_INDEX_HUD_CONFIG,
  ROOT_STATUS_SCORE,
  TOXIC_MODE_COOLDOWN_MS,
  TOXIC_MODE_THRESHOLD,
  TOXICITY_ELEVATED_THRESHOLD,
} from "../risk-engine";
import { MAX_SLIPPAGE, MIN_DEPTH_USD } from "../../../services/risk-control";
import {
  TOPOLOGY_NODE_UI,
  TOPOLOGY_DELTA_CRI_MAX,
  TOPOLOGY_LAMBDA_CRI_MIN,
  EQUILIBRIUM_MODE_UI,
} from "../../../services/vector-equilibrium";
import { HL_RESTRICTED_COUNTRIES, ROLE_LOCK_TIPS, ROLE_TX_THRESHOLDS } from "../step1-engine";
import { DEMO_ROLE_CONFIG } from "../demo-roles";

export function buildClientRuntimeConstantsBlock(): string {
  return `
const DYNAMIC_MAX_SL_BASE_USD = ${DYNAMIC_MAX_SL_BASE_USD};
const DYNAMIC_MAX_SL_BALANCE_RATE = ${DYNAMIC_MAX_SL_BALANCE_RATE};
const DEFAULT_ACCOUNT_EQUITY_USD = ${DEFAULT_ACCOUNT_EQUITY_USD};
const DAILY_LOSS_CAP_MULTIPLIER = ${DAILY_LOSS_CAP_MULTIPLIER};
const MAX_DAILY_SL_COUNT = ${MAX_DAILY_SL_COUNT};
const TOXIC_MODE_THRESHOLD = ${TOXIC_MODE_THRESHOLD};
const TOXICITY_ELEVATED_THRESHOLD = ${TOXICITY_ELEVATED_THRESHOLD};
const TOXIC_MODE_COOLDOWN_MS = ${TOXIC_MODE_COOLDOWN_MS};
const ROLE_TX_THRESHOLDS = ${JSON.stringify(ROLE_TX_THRESHOLDS)};
const ROLE_LOCK_TIPS = ${JSON.stringify(ROLE_LOCK_TIPS)};
const ROOT_DEFENSE_MATRIX_HUD_CONFIG = ${JSON.stringify(ROOT_DEFENSE_MATRIX_HUD_CONFIG)};
const ROOT_DEFENSE_SCORE_MAX = ${ROOT_DEFENSE_SCORE_MAX};
const ROOT_DEFENSE_SCORE_MIN = ${ROOT_DEFENSE_SCORE_MIN};
const ROOT_DEFENSE_OPTIMAL_MIN = ${ROOT_DEFENSE_OPTIMAL_MIN};
const ROOT_DEFENSE_ELEVATED_MIN = ${ROOT_DEFENSE_ELEVATED_MIN};
const TIER_PENALTY_BY_ROOT = ${JSON.stringify(ROOT_DEFENSE_TIER_PENALTY_BY_ROOT)};
const TIER_4_SET = new Set(${JSON.stringify([...ROOT_DEFENSE_TIER_4_ROOTS])});
const RISK_INDEX_HUD_CONFIG = ${JSON.stringify(RISK_INDEX_HUD_CONFIG)};
const ROOT_STATUS_SCORE = ${JSON.stringify(ROOT_STATUS_SCORE)};
const CRI_TIER_DEFINITIONS = ${JSON.stringify(CRI_TIER_DEFINITIONS)};
const MAX_SLIPPAGE = ${MAX_SLIPPAGE};
const MIN_DEPTH_USD = ${MIN_DEPTH_USD};
const HL_RESTRICTED_COUNTRIES = ${JSON.stringify(HL_RESTRICTED_COUNTRIES)};
const DEMO_ROLE_CONFIG = ${JSON.stringify(DEMO_ROLE_CONFIG)};
const TOPOLOGY_NODE_UI = ${JSON.stringify(TOPOLOGY_NODE_UI)};
const EQUILIBRIUM_MODE_UI = ${JSON.stringify(EQUILIBRIUM_MODE_UI)};
const EQUILIBRIUM_DYNAMIC_CRI_MIN = ${EQUILIBRIUM_DYNAMIC_CRI_MIN};
const EQUILIBRIUM_GUARD_CRI_MIN = ${EQUILIBRIUM_GUARD_CRI_MIN};
const ROOT8_SLIPPAGE_LOCK_LABEL = ${JSON.stringify(ROOT8_SLIPPAGE_LOCK_LABEL)};
const R1018_SLIPPAGE_LOCK_LABEL = ${JSON.stringify(R1018_SLIPPAGE_LOCK_LABEL)};
const TOPOLOGY_DELTA_CRI_MAX = ${TOPOLOGY_DELTA_CRI_MAX};
const TOPOLOGY_LAMBDA_CRI_MIN = ${TOPOLOGY_LAMBDA_CRI_MIN};
`.trim();
}
